[project]
name = "t34cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.1.1",
    "httpx>=0.27.2",
    "pydantic>=2.9.2",
    "models==0.1.0"
]

[tool.uv.sources]
models = { workspace = true }

[project.scripts]
t34cli = "t34cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"